# Generated by Django 5.1 on 2024-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_id', models.IntegerField()),
                ('Prod_name', models.CharField(max_length=20)),
                ('Prod_type', models.CharField(max_length=20)),
                ('Prod_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
